In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#data = pd.read_excel('blouse1.xlsx')
data = pd.read_csv("score_result.csv")

In [3]:
data=data.dropna()
data

      Unnamed: 0                                                 리뷰  평점
0              0  그 현장에서 같이 뛰어가는 듯 숨이 차고 안타깝고... 자극적인 장면도 없는데 전쟁...  10
1              1                       배경이 너무 아름답게 펼쳐지지만 전쟁은 너무 참혹함   9
3              3                               전장의 모습을 현실적으로 그려낸 영화  10
4              4                              진짜 전쟁터 안에 들어가있는 기분!!!  10
5              5       단순한 영상미로 그칠 영화가 아니다. 눈요기 말고도 느끼고 생각할게 많은 영화.   9
...          ...                                                ...  ..
4745        4745             촬영이 미쳤습니다 예고편 보지 마시고 가능하면 아이맥스로 관람하세요ㅜ  10
4746        4746  솔직하게 기생충보다 위대한 작품 기생충의 4관왕은 너무 뿌듯하고 축하하지만 순수하게...  10
4747        4747  현장에 들어와 있는 기분이 들고 롱테이크로 몰입감 긴장감이 넘쳤다. 내 기준으로는 ...   9
4748        4748                              촬영감독의 영혼까지 갈아넣은 마스터피스  10
4749        4749  너무 많은 기대를 했던것일까. 소문난 잔치집에 먹을게 없었다. 독특한 촬영기법만으로...   6

[4333 rows x 3 columns]

In [4]:
reference = data
reference

      Unnamed: 0                                                 리뷰  평점
0              0  그 현장에서 같이 뛰어가는 듯 숨이 차고 안타깝고... 자극적인 장면도 없는데 전쟁...  10
1              1                       배경이 너무 아름답게 펼쳐지지만 전쟁은 너무 참혹함   9
3              3                               전장의 모습을 현실적으로 그려낸 영화  10
4              4                              진짜 전쟁터 안에 들어가있는 기분!!!  10
5              5       단순한 영상미로 그칠 영화가 아니다. 눈요기 말고도 느끼고 생각할게 많은 영화.   9
...          ...                                                ...  ..
4745        4745             촬영이 미쳤습니다 예고편 보지 마시고 가능하면 아이맥스로 관람하세요ㅜ  10
4746        4746  솔직하게 기생충보다 위대한 작품 기생충의 4관왕은 너무 뿌듯하고 축하하지만 순수하게...  10
4747        4747  현장에 들어와 있는 기분이 들고 롱테이크로 몰입감 긴장감이 넘쳤다. 내 기준으로는 ...   9
4748        4748                              촬영감독의 영혼까지 갈아넣은 마스터피스  10
4749        4749  너무 많은 기대를 했던것일까. 소문난 잔치집에 먹을게 없었다. 독특한 촬영기법만으로...   6

[4333 rows x 3 columns]

In [5]:
import sister

In [7]:
sentence_embedding = sister.MeanEmbedding(lang="file",fasttextfile="cc.ko.100.bin")

--->
{'en': 'https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.simple.zip', 'ja': 'https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.ja.zip', 'file': 'file1'}
--------- load_model from files :  cc.ko.100.bin

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

In [8]:
data

      Unnamed: 0                                                 리뷰  평점
0              0  그 현장에서 같이 뛰어가는 듯 숨이 차고 안타깝고... 자극적인 장면도 없는데 전쟁...  10
1              1                       배경이 너무 아름답게 펼쳐지지만 전쟁은 너무 참혹함   9
3              3                               전장의 모습을 현실적으로 그려낸 영화  10
4              4                              진짜 전쟁터 안에 들어가있는 기분!!!  10
5              5       단순한 영상미로 그칠 영화가 아니다. 눈요기 말고도 느끼고 생각할게 많은 영화.   9
...          ...                                                ...  ..
4745        4745             촬영이 미쳤습니다 예고편 보지 마시고 가능하면 아이맥스로 관람하세요ㅜ  10
4746        4746  솔직하게 기생충보다 위대한 작품 기생충의 4관왕은 너무 뿌듯하고 축하하지만 순수하게...  10
4747        4747  현장에 들어와 있는 기분이 들고 롱테이크로 몰입감 긴장감이 넘쳤다. 내 기준으로는 ...   9
4748        4748                              촬영감독의 영혼까지 갈아넣은 마스터피스  10
4749        4749  너무 많은 기대를 했던것일까. 소문난 잔치집에 먹을게 없었다. 독특한 촬영기법만으로...   6

[4333 rows x 3 columns]

In [9]:
def review_embedding(df): #리뷰를 100차원의 값으로 임베딩
    df_rev = df['리뷰']
    r_list=df_rev.values.tolist()
    vector1_list = []

    for i in range(len(r_list)): 
    
        s1 = sentence_embedding(r_list[i])
        vector1_list.append(s1)
        
        
    vector_df= pd.DataFrame(vector1_list) #DataFrame으로
    return vector_df #merge

In [10]:
res_df=review_embedding(data)
res_df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.053464,-0.334112,0.048654,0.074649,-0.142712,0.087131,0.028596,0.078053,-0.131117,-0.050879,...,-0.037497,0.001423,0.040081,-0.012148,0.007088,-0.020943,-0.026379,-0.021574,0.040718,2.826132e-02
1,0.024297,-0.258987,-0.131318,0.006122,-0.162488,0.093422,0.038213,0.050326,-0.148258,-0.070781,...,-0.022014,0.001828,0.017006,0.051842,0.036084,-0.013424,0.005900,-0.014123,0.018963,3.889507e-02
2,-0.121291,-0.239516,-0.053116,0.019461,-0.004792,0.103001,0.060964,0.010130,0.134573,0.072880,...,-0.006017,0.008253,-0.008799,-0.016961,-0.060213,0.015836,0.002849,-0.017529,0.029476,3.718346e-03
3,-0.280262,-0.447320,0.106383,0.024981,-0.119354,0.114955,0.152714,0.205347,0.017616,-0.048235,...,-0.037043,-0.028030,0.080916,0.007988,-0.039548,-0.113525,-0.038055,-0.030768,0.054832,3.178664e-02
4,-0.019125,-0.329724,0.031745,-0.001870,-0.022598,0.115848,0.023184,0.091767,-0.075323,-0.005498,...,-0.007455,-0.013281,-0.018867,0.013162,-0.025232,-0.008227,-0.022899,0.012680,0.037997,-1.483701e-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4328,0.016639,-0.257168,0.078995,0.018158,-0.079549,-0.035762,0.098111,0.083851,-0.013289,-0.017888,...,0.005120,-0.061088,-0.004192,-0.003533,0.002732,0.034629,-0.030029,-0.004948,0.020410,7.057035e-02
4329,-0.002700,-0.333255,-0.024951,-0.012317,-0.121600,0.063221,0.034465,0.040346,-0.026012,-0.059297,...,0.015486,0.022436,-0.025364,0.015348,0.011676,-0.001595,-0.006583,0.001280,0.008283,5.666231e-02
4330,0.004574,-0.336279,0.047474,0.032508,-0.098674,-0.027613,0.057299,0.069918,-0.042222,-0.009095,...,-0.052099,0.001019,0.014972,0.018685,0.012873,-0.041004,-0.019596,0.016491,0.042812,2.862969e-02
4331,-0.046628,-0.049401,0.037605,0.003017,-0.101339,0.051194,0.100310,0.045217,0.040765,0.084925,...,0.037565,-0.001193,-0.002286,0.021051,-0.003683,-0.003925,-0.036339,0.020033,0.014967,4.826627e-03
4332,-0.013860,-0.239205,0.034623,0.023188,-0.099596,0.047580,0.032729,0.036536,-0.069520,-0.022859,...,-0.018632,-0.004143,-0.002503,0.010083,0.019000,0.025277,0.015878,0.003586,0.016953,-6.758741e-07

In [11]:
sc=data[['평점']].values.tolist()
sco_df=pd.DataFrame(sc)
sco_df.columns = ['평점']
sco_df

      평점
0     10
1      9
2     10
3     10
4      9
...   ..
4328  10
4329  10
4330   9
4331  10
4332   6

[4333 rows x 1 columns]

In [12]:
result=pd.concat([res_df,sco_df],axis= 1)
result

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,평점
0,-0.053464,-0.334112,0.048654,0.074649,-0.142712,0.087131,0.028596,0.078053,-0.131117,-0.050879,...,0.001423,0.040081,-0.012148,0.007088,-0.020943,-0.026379,-0.021574,0.040718,2.826132e-02,10
1,0.024297,-0.258987,-0.131318,0.006122,-0.162488,0.093422,0.038213,0.050326,-0.148258,-0.070781,...,0.001828,0.017006,0.051842,0.036084,-0.013424,0.005900,-0.014123,0.018963,3.889507e-02,9
2,-0.121291,-0.239516,-0.053116,0.019461,-0.004792,0.103001,0.060964,0.010130,0.134573,0.072880,...,0.008253,-0.008799,-0.016961,-0.060213,0.015836,0.002849,-0.017529,0.029476,3.718346e-03,10
3,-0.280262,-0.447320,0.106383,0.024981,-0.119354,0.114955,0.152714,0.205347,0.017616,-0.048235,...,-0.028030,0.080916,0.007988,-0.039548,-0.113525,-0.038055,-0.030768,0.054832,3.178664e-02,10
4,-0.019125,-0.329724,0.031745,-0.001870,-0.022598,0.115848,0.023184,0.091767,-0.075323,-0.005498,...,-0.013281,-0.018867,0.013162,-0.025232,-0.008227,-0.022899,0.012680,0.037997,-1.483701e-02,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4328,0.016639,-0.257168,0.078995,0.018158,-0.079549,-0.035762,0.098111,0.083851,-0.013289,-0.017888,...,-0.061088,-0.004192,-0.003533,0.002732,0.034629,-0.030029,-0.004948,0.020410,7.057035e-02,10
4329,-0.002700,-0.333255,-0.024951,-0.012317,-0.121600,0.063221,0.034465,0.040346,-0.026012,-0.059297,...,0.022436,-0.025364,0.015348,0.011676,-0.001595,-0.006583,0.001280,0.008283,5.666231e-02,10
4330,0.004574,-0.336279,0.047474,0.032508,-0.098674,-0.027613,0.057299,0.069918,-0.042222,-0.009095,...,0.001019,0.014972,0.018685,0.012873,-0.041004,-0.019596,0.016491,0.042812,2.862969e-02,9
4331,-0.046628,-0.049401,0.037605,0.003017,-0.101339,0.051194,0.100310,0.045217,0.040765,0.084925,...,-0.001193,-0.002286,0.021051,-0.003683,-0.003925,-0.036339,0.020033,0.014967,4.826627e-03,10
4332,-0.013860,-0.239205,0.034623,0.023188,-0.099596,0.047580,0.032729,0.036536,-0.069520,-0.022859,...,-0.004143,-0.002503,0.010083,0.019000,0.025277,0.015878,0.003586,0.016953,-6.758741e-07,6

In [13]:
#벡터값 정규화(100챠원 리뷰 + 1차원 평점)
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
fitted = min_max_scaler.fit(result)
print(fitted.data_max_)
## 출력 결과
## [891.       1.       3.      80.       8.       6.     512.3292]
output = min_max_scaler.transform(result)
output = pd.DataFrame(output, columns=result.columns, index=list(result.index.values))
output.head()

[ 0.19283164  0.05622385  0.39025986  0.37203988  0.23402929  0.38279182
  0.43838459  0.4613224   0.52074522  0.72498018  0.25132146  0.21031669
  0.25367561  0.20135053  0.21454531  0.27527404  0.21335003  0.15581313
  0.46431756  0.41206071  0.20272523  0.21960784  0.33184224  0.33681807
  0.13956609  0.30766621  0.19377612  0.29703686  0.34232318  0.24203041
  0.21660356  0.26296669  0.24043749  0.65046531  0.2777319   0.14962038
  0.2851657   0.25057256  0.09326989  0.40948918  0.32756767  0.17853935
  0.24260299  0.27507055  0.17921793  0.13400397  0.27908689  0.30989209
  0.07099711  1.21506119  0.15886725  0.28319576  0.16485612  0.21882486
  0.26680073  0.38073108  0.34093565  0.26913977  0.15880363  0.36208564
  0.21569982  0.55004108  0.26268783  0.15013143  0.21037954  0.19820032
  0.2028698   0.16808054  0.1923276   0.23138741  0.30365738  0.30602372
  0.25725168  0.16920409  0.36689216  0.22371113  0.3098354   0.18096475
  0.13858552  0.1568362   0.15553126  0.19495496  0.13457496  0.16245018
  0.30008253  0.08973692  0.2288522   0.17886418  0.12393932  0.24418698
  0.19713865  0.19042277  0.15668643  0.31146991  0.11500426  0.13653663
  0.25778377  0.26106471  0.48578736  0.1902891  10.        ]

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,평점
0,0.827219,0.575462,0.432236,0.551701,0.517107,0.483983,0.446296,0.391036,0.240262,0.222241,...,0.478321,0.771736,0.312679,0.629418,0.487988,0.456255,0.416470,0.223261,0.659958,1.000000
1,0.881770,0.657169,0.133113,0.448400,0.491759,0.494964,0.459290,0.346982,0.220285,0.202290,...,0.479438,0.726566,0.448585,0.728990,0.512436,0.518020,0.431852,0.185296,0.682275,0.888889
2,0.779637,0.678347,0.263088,0.468508,0.693888,0.511681,0.490032,0.283117,0.549921,0.346302,...,0.497172,0.676049,0.302457,0.398305,0.607568,0.512182,0.424822,0.203643,0.608451,1.000000
3,0.668116,0.452334,0.528182,0.476829,0.547046,0.532545,0.614004,0.593290,0.413608,0.224892,...,0.397026,0.851673,0.355446,0.469267,0.186977,0.433913,0.397488,0.247893,0.667356,1.000000
4,0.851308,0.580235,0.404132,0.436353,0.671065,0.534102,0.438984,0.412825,0.305290,0.267733,...,0.437734,0.656341,0.366435,0.518430,0.529332,0.462912,0.487189,0.218513,0.569509,0.888889

In [14]:
output

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,평점
0,0.827219,0.575462,0.432236,0.551701,0.517107,0.483983,0.446296,0.391036,0.240262,0.222241,...,0.478321,0.771736,0.312679,0.629418,0.487988,0.456255,0.416470,0.223261,0.659958,1.000000
1,0.881770,0.657169,0.133113,0.448400,0.491759,0.494964,0.459290,0.346982,0.220285,0.202290,...,0.479438,0.726566,0.448585,0.728990,0.512436,0.518020,0.431852,0.185296,0.682275,0.888889
2,0.779637,0.678347,0.263088,0.468508,0.693888,0.511681,0.490032,0.283117,0.549921,0.346302,...,0.497172,0.676049,0.302457,0.398305,0.607568,0.512182,0.424822,0.203643,0.608451,1.000000
3,0.668116,0.452334,0.528182,0.476829,0.547046,0.532545,0.614004,0.593290,0.413608,0.224892,...,0.397026,0.851673,0.355446,0.469267,0.186977,0.433913,0.397488,0.247893,0.667356,1.000000
4,0.851308,0.580235,0.404132,0.436353,0.671065,0.534102,0.438984,0.412825,0.305290,0.267733,...,0.437734,0.656341,0.366435,0.518430,0.529332,0.462912,0.487189,0.218513,0.569509,0.888889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4328,0.876398,0.659148,0.482662,0.466544,0.598067,0.269499,0.540224,0.400249,0.377589,0.255313,...,0.305777,0.685069,0.330976,0.614458,0.668671,0.449270,0.450796,0.187820,0.748750,1.000000
4329,0.862831,0.576394,0.309899,0.420605,0.544167,0.442254,0.454226,0.331125,0.362761,0.213802,...,0.536320,0.643622,0.371077,0.645171,0.550893,0.494134,0.463653,0.166656,0.719562,1.000000
4330,0.867934,0.573105,0.430274,0.488177,0.573552,0.283720,0.485079,0.378111,0.343868,0.264127,...,0.477206,0.722583,0.378165,0.649281,0.422763,0.469233,0.495058,0.226916,0.660731,0.888889
4331,0.832015,0.885121,0.413871,0.443720,0.570137,0.421263,0.543195,0.338865,0.440589,0.358377,...,0.471099,0.688799,0.383189,0.592430,0.543320,0.437196,0.502370,0.178321,0.610776,1.000000
4332,0.855002,0.678685,0.408914,0.474126,0.572372,0.414955,0.451880,0.325072,0.312053,0.250329,...,0.462958,0.688375,0.359895,0.670323,0.638263,0.537113,0.468414,0.181787,0.600646,0.555556

In [15]:
import scipy
from scipy import io

In [16]:
output.to_csv('movie_review_100_4174.csv',index=None) #csv파일로 저장